spring.application.name=procurehub
spring.datasource.url=jdbc:mysql://localhost:3306/procurehub
spring.datasource.username=root
spring.datasource.password=shivi@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shibupatel013@gmail.com
spring.mail.password=yvdc ueud sxzy aasr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true